services:
  gophermart:
    build:
      context: ..
      dockerfile: build/gophermart.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gophermart-network
  accrual:
    build:
      context: ..
      dockerfile: build/accrual.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      DATABASE_URI: "postgres://postgres_user:postgres_password@postgres:5432/postgres_db?sslmode=disable"
    networks:
      - gophermart-network

  postgres:
    image: postgres:17
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gophermart-network

  adminer:
    image: adminer:standalone
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - gophermart-network

volumes:
  postgres-data:


networks:
  gophermart-network:
    driver: bridge
